MagicCurls/grace-shopper

- public/index.html
> Add Khalid_Dev Branch

- package.json
I am changing repo name to "grace-shopper"
> trying to make git conflict

- .travis.yml
> .travis.yml before_script name change

- MergeConflictFile.txt
> Merge Conflict file added

- MergeConflictFile.txt
> changed to Magic Curls

- MergeConflictFile.txt
> Khalid dev

- MergeConflictFile.txt
> merge conflict added

- package-lock.json
> client directory files added

- server/api/carts.js
- server/api/index.js
- server/db/models/cartEntry.js
- server/db/models/index.js
> Add route to get all products in a user's cart

- client/store/cart.js
- client/store/navbar.js
- client/store/productList.js
- client/store/singleProduct.js
reducers action and action creators are added
> actins, action creators

- .gitignore
- server/api/index.js
- server/api/robots.js
- server/db/db.js
- server/db/models/robot.js
- server/db/models/robot.spec.js
> Robots model, model test specs, api

- server/api/robots.spec.js
- server/db/db.js
> Created test specs for Robots API

- client/components/FullCartList.js
- client/components/FullRobotList.js
> updated thunk funcs in react

- client/components/FullRobotList.js
> fixed add thunk func

- client/components/FullCartList.js
- client/components/FullRobotList.js
- client/components/ListComponent.js
- client/components/RobotPreview.js
- client/components/UpdateRemove.js
- client/components/UpdateRemoveForm.js
- client/store/cart.js
- server/api/carts.js
> working besides removeFromCart

- client/components/UpdateRemoveForm.js
- package-lock.json
> fix default quantity display in cart

- client/components/UpdateRemove.js
- client/components/UpdateRemoveForm.js
- package-lock.json
> slight updates to update

- client/components/FullCartList.js
- client/components/ListComponent.js
- client/components/UpdateRemove.js
> quantity updating without refresh

- client/components/AddToCart.js
- client/components/FullRobotList.js
- client/components/ListComponent.js
- client/store/guestCart.js
- client/store/index.js
- package-lock.json
> local storage attempt

- client/store/completedOrders.js
- server/index.js
> Stripe Secrets protected

- server/index.js
> Stripe Secrets protected (update)

- server/api/completedOrders.spec.js
> completedOrder spec second commit
